services:
  devcontainer:
    image: env-decorators-devcontainer
    container_name: env-decorators-devcontainer
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    runtime: runsc
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - ../../env-decorators/:/workspace:cached
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2gb